### ISSUE TITLE
Change the return value of unset elements

### ISSUE THREAD

**Issue by qur2** [TylorS/cycle-local-storage#1]
Hi,

Maybe I'm doing something wrong, in which case I'd appreciate your enlightenment :)
Basically I would like to get a storage item with a default value if unset. I naturally started to use `defaultIfEmpty` from `Rx`. Unfortunately, when getting an unset key, local storage returns `null` but `Rx` tests against `undefined`:
```js
defaultValue === undefined && (defaultValue = null) //see https://github.com/Reactive-Extensions/RxJS/blob/985f1eb9bc4bd6033213b4fc5a6a23375fa710d8/src/core/linq/observable/defaultifempty.js
```

This make the following snippet to misbehave:
```js
Store.get('my key').defaultIfEmpty('default value'); // null !== undefined
```

In order to make this observable behave like any other, I think it should return undefined rather than null when the key is unset.

**Comment by TylorS** [comment]
Ahhh, this is one of those situations where my (lack of) knowledge on Rx bites me in the butt. Going through the docs you make a valid point :+1: 

Thanks for the issue, I'll change this behavior in a few minutes.

**Comment by TylorS** [comment]
This is a curious thing, because returning `undefined` instead of `null` does not solve this problem.

**Comment by TylorS** [comment]
It's likely because I use a subject internally, a behaviourSubject to be precise, with the default value of `localStorage`. Thus it is technically never empty.

**Comment by TylorS** [comment]
This should now work with 954dbb9e17f640cf3680261379deece1a76c525e and npm version 1.1.0

Let me know if it's working on your end, and that it's safe to close this issue.

**Comment by TylorS** [comment]
A word of caution, if you're using an array in `.get()` it will still return `null` as the value for unspecified keys.

**Comment by qur2** [comment]
Hey, that was very speedy, thanks!

I tried the quick fix and saw it was not helping as well. Seem like your Rx know-how is better than mine :p
Anyway your change is working for me know. I also wanted to add a test, but then I'm not familiar with the libraries you're using at all.

**Comment by TylorS** [comment]
I'm using https://github.com/substack/tape for tests on this library.

**Comment by TylorS** [comment]
I did add a test for this use case

**Comment by qur2** [comment]
Never heard of tape before, that was a very informative issue, thanks!
