### ISSUE TITLE
How do you set value?

### ISSUE THREAD

**Issue by qur2** [TylorS/cycle-local-storage#2]
Hi,

It's probably an issue of me not being familiar with Cycle.js drivers, but I just don't get how to change value in the local storage through the driver (which I assume is necessary in order to observe the new values).
Can you help me with that?

Thanks!

**Comment by TylorS** [comment]
From you main function you should be returning an observable which should have the key:value pairs you would like to set.
```js
function main(drivers) {
  ...
  let storage$ = Rx.Observable.just({
   "key1": "value1",
   "key2": "value2",
  });

  return {
    Storage: storage$,
  }
}
```
Of course you wouldn't want to use a `.just()` observable, but one that you can manipulate over time.

**Comment by TylorS** [comment]
You can also return an array of Objects from the observable. 
```js
Rx.Observable.just(
  [
    {"key1": "value1"},
    {"key2": "value2"},
  ]
);
```

**Comment by TylorS** [comment]
Apologies, I may have introduced a bug fixing our last issue. I'm looking to rectify it now.

**Comment by qur2** [comment]
Hi, thanks for the explanation, at least I'm on the right track now :) Still bending my head around this whole reactive thing. I find it hard to cleanly separate intents and models and keeping the main function clean.

**Comment by TylorS** [comment]
It will come in time. I think the issue I created has been fixed :smile:

**Comment by TylorS** [comment]
I added a test case for it as well. Is it safe to close this issue? Or is there anything else?

**Comment by qur2** [comment]
Closing, thanks a lot!

**Comment by TylorS** [comment]
No problem
